-- Country dropdown (admin-editable via Settings), plus normalizing existing data.
INSERT INTO picklist_values (field_name, value, sort_order) VALUES
  ('country', 'Afghanistan', 10),
  ('country', 'Albania', 20),
  ('country', 'Algeria', 30),
  ('country', 'American Samoa', 40),
  ('country', 'Andorra', 50),
  ('country', 'Angola', 60),
  ('country', 'Anguilla', 70),
  ('country', 'Antigua and Barbuda', 80),
  ('country', 'Argentina', 90),
  ('country', 'Armenia', 100),
  ('country', 'Aruba', 110),
  ('country', 'Australia', 120),
  ('country', 'Austria', 130),
  ('country', 'Azerbaijan', 140),
  ('country', 'Bahamas', 150),
  ('country', 'Bahrain', 160),
  ('country', 'Bangladesh', 170),
  ('country', 'Barbados', 180),
  ('country', 'Belarus', 190),
  ('country', 'Belgium', 200),
  ('country', 'Belize', 210),
  ('country', 'Benin', 220),
  ('country', 'Bermuda', 230),
  ('country', 'Bhutan', 240),
  ('country', 'Bolivia', 250),
  ('country', 'Bosnia and Herzegovina', 260),
  ('country', 'Botswana', 270),
  ('country', 'Brazil', 280),
  ('country', 'British Indian Ocean Territory', 290),
  ('country', 'British Virgin Islands', 300),
  ('country', 'Brunei', 310),
  ('country', 'Bulgaria', 320),
  ('country', 'Burkina Faso', 330),
  ('country', 'Burundi', 340),
  ('country', 'Cabo Verde', 350),
  ('country', 'Cambodia', 360),
  ('country', 'Cameroon', 370),
  ('country', 'Canada', 380),
  ('country', 'Caribbean Netherlands', 390),
  ('country', 'Cayman Islands', 400),
  ('country', 'Central African Republic', 410),
  ('country', 'Chad', 420),
  ('country', 'Chile', 430),
  ('country', 'China', 440),
  ('country', 'Christmas Island', 450),
  ('country', 'Cocos (Keeling) Islands', 460),
  ('country', 'Colombia', 470),
  ('country', 'Comoros', 480),
  ('country', 'Congo', 490),
  ('country', 'Congo (DRC)', 500),
  ('country', 'Cook Islands', 510),
  ('country', 'Costa Rica', 520),
  ('country', 'Croatia', 530),
  ('country', 'Cuba', 540),
  ('country', 'Curaçao', 550),
  ('country', 'Cyprus', 560),
  ('country', 'Czechia', 570),
  ('country', 'Denmark', 580),
  ('country', 'Djibouti', 590),
  ('country', 'Dominica', 600),
  ('country', 'Dominican Republic', 610),
  ('country', 'Ecuador', 620),
  ('country', 'Egypt', 630),
  ('country', 'El Salvador', 640),
  ('country', 'Equatorial Guinea', 650),
  ('country', 'Eritrea', 660),
  ('country', 'Estonia', 670),
  ('country', 'Eswatini', 680),
  ('country', 'Ethiopia', 690),
  ('country', 'Falkland Islands', 700),
  ('country', 'Faroe Islands', 710),
  ('country', 'Fiji', 720),
  ('country', 'Finland', 730),
  ('country', 'France', 740),
  ('country', 'French Guiana', 750),
  ('country', 'French Polynesia', 760),
  ('country', 'Gabon', 770),
  ('country', 'Gambia', 780),
  ('country', 'Georgia', 790),
  ('country', 'Germany', 800),
  ('country', 'Ghana', 810),
  ('country', 'Gibraltar', 820),
  ('country', 'Greece', 830),
  ('country', 'Greenland', 840),
  ('country', 'Grenada', 850),
  ('country', 'Guadeloupe', 860),
  ('country', 'Guam', 870),
  ('country', 'Guatemala', 880),
  ('country', 'Guernsey', 890),
  ('country', 'Guinea', 900),
  ('country', 'Guinea-Bissau', 910),
  ('country', 'Guyana', 920),
  ('country', 'Haiti', 930),
  ('country', 'Honduras', 940),
  ('country', 'Hong Kong', 950),
  ('country', 'Hungary', 960),
  ('country', 'Iceland', 970),
  ('country', 'India', 980),
  ('country', 'Indonesia', 990),
  ('country', 'Iran', 1000),
  ('country', 'Iraq', 1010),
  ('country', 'Ireland', 1020),
  ('country', 'Isle of Man', 1030),
  ('country', 'Israel', 1040),
  ('country', 'Italy', 1050),
  ('country', 'Ivory Coast', 1060),
  ('country', 'Jamaica', 1070),
  ('country', 'Japan', 1080),
  ('country', 'Jersey', 1090),
  ('country', 'Jordan', 1100),
  ('country', 'Kazakhstan', 1110),
  ('country', 'Kenya', 1120),
  ('country', 'Kiribati', 1130),
  ('country', 'Kuwait', 1140),
  ('country', 'Kyrgyzstan', 1150),
  ('country', 'Laos', 1160),
  ('country', 'Latvia', 1170),
  ('country', 'Lebanon', 1180),
  ('country', 'Lesotho', 1190),
  ('country', 'Liberia', 1200),
  ('country', 'Libya', 1210),
  ('country', 'Liechtenstein', 1220),
  ('country', 'Lithuania', 1230),
  ('country', 'Luxembourg', 1240),
  ('country', 'Macao', 1250),
  ('country', 'Madagascar', 1260),
  ('country', 'Malawi', 1270),
  ('country', 'Malaysia', 1280),
  ('country', 'Maldives', 1290),
  ('country', 'Mali', 1300),
  ('country', 'Malta', 1310),
  ('country', 'Marshall Islands', 1320),
  ('country', 'Martinique', 1330),
  ('country', 'Mauritania', 1340),
  ('country', 'Mauritius', 1350),
  ('country', 'Mayotte', 1360),
  ('country', 'Mexico', 1370),
  ('country', 'Micronesia', 1380),
  ('country', 'Moldova', 1390),
  ('country', 'Monaco', 1400),
  ('country', 'Mongolia', 1410),
  ('country', 'Montenegro', 1420),
  ('country', 'Montserrat', 1430),
  ('country', 'Morocco', 1440),
  ('country', 'Mozambique', 1450),
  ('country', 'Myanmar', 1460),
  ('country', 'Namibia', 1470),
  ('country', 'Nauru', 1480),
  ('country', 'Nepal', 1490),
  ('country', 'Netherlands', 1500),
  ('country', 'New Caledonia', 1510),
  ('country', 'New Zealand', 1520),
  ('country', 'Nicaragua', 1530),
  ('country', 'Niger', 1540),
  ('country', 'Nigeria', 1550),
  ('country', 'Niue', 1560),
  ('country', 'Norfolk Island', 1570),
  ('country', 'North Korea', 1580),
  ('country', 'North Macedonia', 1590),
  ('country', 'Northern Mariana Islands', 1600),
  ('country', 'Norway', 1610),
  ('country', 'Oman', 1620),
  ('country', 'Pakistan', 1630),
  ('country', 'Palau', 1640),
  ('country', 'Palestine', 1650),
  ('country', 'Panama', 1660),
  ('country', 'Papua New Guinea', 1670),
  ('country', 'Paraguay', 1680),
  ('country', 'Peru', 1690),
  ('country', 'Philippines', 1700),
  ('country', 'Pitcairn Islands', 1710),
  ('country', 'Poland', 1720),
  ('country', 'Portugal', 1730),
  ('country', 'Puerto Rico', 1740),
  ('country', 'Qatar', 1750),
  ('country', 'Réunion', 1760),
  ('country', 'Romania', 1770),
  ('country', 'Russia', 1780),
  ('country', 'Rwanda', 1790),
  ('country', 'Saint Kitts and Nevis', 1800),
  ('country', 'Saint Lucia', 1810),
  ('country', 'Saint Vincent and the Grenadines', 1820),
  ('country', 'Samoa', 1830),
  ('country', 'San Marino', 1840),
  ('country', 'Sao Tome and Principe', 1850),
  ('country', 'Saudi Arabia', 1860),
  ('country', 'Senegal', 1870),
  ('country', 'Serbia', 1880),
  ('country', 'Seychelles', 1890),
  ('country', 'Sierra Leone', 1900),
  ('country', 'Singapore', 1910),
  ('country', 'Sint Maarten', 1920),
  ('country', 'Slovakia', 1930),
  ('country', 'Slovenia', 1940),
  ('country', 'Solomon Islands', 1950),
  ('country', 'Somalia', 1960),
  ('country', 'South Africa', 1970),
  ('country', 'South Korea', 1980),
  ('country', 'South Sudan', 1990),
  ('country', 'Spain', 2000),
  ('country', 'Sri Lanka', 2010),
  ('country', 'St. Barthélemy', 2020),
  ('country', 'St. Helena', 2030),
  ('country', 'St. Martin', 2040),
  ('country', 'St. Pierre & Miquelon', 2050),
  ('country', 'Sudan', 2060),
  ('country', 'Suriname', 2070),
  ('country', 'Svalbard & Jan Mayen', 2080),
  ('country', 'Sweden', 2090),
  ('country', 'Switzerland', 2100),
  ('country', 'Syria', 2110),
  ('country', 'Taiwan', 2120),
  ('country', 'Tajikistan', 2130),
  ('country', 'Tanzania', 2140),
  ('country', 'Thailand', 2150),
  ('country', 'Timor-Leste', 2160),
  ('country', 'Togo', 2170),
  ('country', 'Tokelau', 2180),
  ('country', 'Tonga', 2190),
  ('country', 'Trinidad and Tobago', 2200),
  ('country', 'Tunisia', 2210),
  ('country', 'Turkey', 2220),
  ('country', 'Turkmenistan', 2230),
  ('country', 'Turks and Caicos Islands', 2240),
  ('country', 'Tuvalu', 2250),
  ('country', 'U.S. Virgin Islands', 2260),
  ('country', 'Uganda', 2270),
  ('country', 'Ukraine', 2280),
  ('country', 'United Arab Emirates', 2290),
  ('country', 'United Kingdom', 2300),
  ('country', 'United States', 2310),
  ('country', 'Uruguay', 2320),
  ('country', 'Uzbekistan', 2330),
  ('country', 'Vanuatu', 2340),
  ('country', 'Vatican City', 2350),
  ('country', 'Venezuela', 2360),
  ('country', 'Vietnam', 2370),
  ('country', 'Wallis & Futuna', 2380),
  ('country', 'Western Sahara', 2390),
  ('country', 'Yemen', 2400),
  ('country', 'Zambia', 2410),
  ('country', 'Zimbabwe', 2420)
ON CONFLICT DO NOTHING;

-- Normalize legacy country spellings to the dropdown values.
UPDATE companies SET country = 'United States' WHERE lower(country) IN ('usa', 'us', 'u.s.', 'u.s.a.', 'united states of america');
UPDATE companies SET country = 'United Kingdom' WHERE lower(country) IN ('uk', 'u.k.', 'great britain', 'england', 'scotland', 'wales');

-- Backfill legacy lifecycle_stage values to the current dropdown values.
UPDATE companies SET lifecycle_stage = 'Lead' WHERE lifecycle_stage = 'Prospect';
UPDATE companies SET lifecycle_stage = 'Sales Qualified' WHERE lifecycle_stage = 'Sales Qualified Lead';
